/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MaskLazyImport = createFileRoute('/mask')()
const ConditionalFieldsLazyImport = createFileRoute('/conditional-fields')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MaskLazyRoute = MaskLazyImport.update({
  path: '/mask',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mask.lazy').then((d) => d.Route))

const ConditionalFieldsLazyRoute = ConditionalFieldsLazyImport.update({
  path: '/conditional-fields',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/conditional-fields.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/conditional-fields': {
      id: '/conditional-fields'
      path: '/conditional-fields'
      fullPath: '/conditional-fields'
      preLoaderRoute: typeof ConditionalFieldsLazyImport
      parentRoute: typeof rootRoute
    }
    '/mask': {
      id: '/mask'
      path: '/mask'
      fullPath: '/mask'
      preLoaderRoute: typeof MaskLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ConditionalFieldsLazyRoute,
  MaskLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/conditional-fields",
        "/mask"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/conditional-fields": {
      "filePath": "conditional-fields.lazy.tsx"
    },
    "/mask": {
      "filePath": "mask.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
